apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tl5ec645q-go
  janus-idp.io/tekton: tl5ec645q-go
  backstage.io/kubernetes-id: tl5ec645q-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tl5ec645q-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
